---
urls:
  - https://www.bestbuy.com/site/evga-geforce-rtx-3080-ftw3-gaming-10gb-gddr6x-pci-express-4-0-graphics-card/6436191.p?skuId=6436191
  - https://www.bestbuy.com/site/evga-geforce-rtx-3090-ftw3-gaming-24gb-gddr6-pci-express-4-0-graphics-card/6436193.p?skuId=6436193
  - https://www.bestbuy.com/site/gigabyte-nvidia-geforce-rtx-3080-vision-oc-10gb-gddr6x-pci-express-4-0-graphics-card/6436219.p?skuId=6436219
  - https://www.newegg.com/asus-geforce-rtx-3080-rog-strix-rtx3080-o10g-white/p/N82E16814126483
  - https://www.newegg.com/asus-geforce-rtx-3090-rog-strix-rtx3090-o24g-white/p/N82E16814126482?Item=N82E16814126482
  - https://smile.amazon.com/ASUS-Graphics-DisplayPort-Military-Grade-Certification/dp/B08HH5WF97
  - https://smile.amazon.com/MSI-GeForce-RTX-3080-10G/dp/B08HR7SV3M
  - https://smile.amazon.com/Gigabyte-Graphics-WINDFORCE-Protection-DisplayPort/dp/B08WJJNT2R
  - https://smile.amazon.com/Gigabyte-Graphics-WINDFORCE-Protection-DisplayPort/dp/B08WJJ7962
  - https://smile.amazon.com/GIGABYTE-Graphics-WINDFORCE-GV-N3070VISION-OC-8GD/dp/B08M13DXSZ
  - https://smile.amazon.com/ASUS-Graphics-DisplayPort-Axial-tech-2-9-Slot/dp/B08J6GMWCQ
  - https://smile.amazon.com/EVGA-GeForce-Technology-Backplate-24G-P5-3987-KR/dp/B08J5F3G18
  - https://smile.amazon.com/GeForce-Graphics-Technology-Backplate-DisplayPort/dp/B08W2BNR9D
  - https://smile.amazon.com/GeForce-Graphics-Technology-Backplate-DisplayPort/dp/B08W2DF4KS
  - https://smile.amazon.com/GeForce-Gaming-Graphics-Technology-Backplate/dp/B08W1VRQ4V
  - https://smile.amazon.com/EVGA-GeForce-Technology-Backplate-24G-P5-3987-KR/dp/B08J5F3G18
  - https://smile.amazon.com/ASUS-Graphics-DisplayPort-Axial-Tech-2-9-Slot/dp/B08J6GMWCQ
  - https://smile.amazon.com/PNY-GeForce-3090-24GB-XLR8/dp/B08HBVX53D
  - https://smile.amazon.com/MSI-GeForce-RTX-3090-VENTUS/dp/B08HR9D2JS
  - https://smile.amazon.com/ASUS-GeForce-Graphics-DisplayPort-Bearings/dp/B08HJGNJ81
...
